server:
  port: 9090
spring:
  profiles:
    include: oauth #,db
  application:
    name: userservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/devstagram #mongodb://localhost:17017/devstagram
      #authentication-database: admin



logging:
  level:
    org.springframework.data.mongodb: DEBUG





      #  profiles:
      #    active: default
      #  config:
      #    import: "optional:configserver:http://localhost:8888"
