server:
  port: 9090
spring:
  profiles:
    include: db
  application:
    name: userservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/devstagram
      authentication-database: admin


      #  profiles:
      #    active: default
      #  config:
      #    import: "optional:configserver:http://localhost:8888"
