server:
  port: 9999
spring:
  application:
    name: gatewayservice
  profiles:
    active: default
  config:
    import: "optional:configserver:http://localhost:8888"
    #use-legacy-processing: true #unable to laod config data 오류 발생 시 사용

