uri:
  user-service: "http://localhost:9090"
  post-service: "http://localhost:9091"
  meetup-service: "http://localhost:9092"
server:
  port: 9999
spring:
  application:
    name: gatewayservice
  profiles:
    active: default
  config:
    import: "optional:configserver:"
    #use-legacy-processing: true #unable to laod config data 오류 발생 시 사용
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
      routes:
        - id: user-service
          uri: ${uri.user-service}
          predicates:
            - Path=/api/user/profile/**
          filters:
            - RewritePath=/api/user/profile/(?<path>.*),/$\{path}
            - UserJwtFilter
        - id: post-service
          uri: ${uri.post-service}
          predicates:
            - Path=/api/posts/**
          filters:
            - RewritePath=/api/posts/(?<path>.*),/$\{path}
            - UserJwtFilter
        - id: meetup-service
          uri: ${uri.meetup-service}
          predicates:
            - Path=/api/meetup/service/**
          filters:
            - RewritePath=/api/meetup/(?<path>.*),/$\{path}
            - UserJwtFilter
        - id: meetup-read
          uri: ${uri.meetup-service}
          predicates:
            - Path=/api/meetup/read/**
          filters:
            - RewritePath=/api/meetup/(?<path>.*),/$\{path}

jwt:
  secret: moondysmellwebapplicationsecret
  expiration-second: 172800  #48시간
#  expiration-second: 259200  #72시간
#  expiration-second: 10  #10초

#### cloud 용
#  user-service: http://198.19.142.213:9090
#  post-service: http://198.19.239.141:9091
#  meetup-service: http://198.19.196.12:9092

