uri:
  user-service: "http://localhost:9090"
  post-service: "http://localhost:9091"
server:
  port: 9999
spring:
  application:
    name: gatewayservice
  profiles:
    active: default
  config:
    import: "optional:configserver:"
    #use-legacy-processing: true #unable to laod config data 오류 발생 시 사용
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - PUT
              - GET
              - POST
      routes:
        - id: user-service
          uri: ${uri.user-service}
          predicates:
            - Path=/api/user/profile/**
          filters:
            - RewritePath=/api/user/(?<path>.*),/$\{path}
            - UserJwtFilter
        - id: post-service
          uri: ${uri.post-service}
          predicates:
            - Path=/api/user/posts/**
          filters:
            - RewritePath=/api/user/(?<path>.*),/$\{path}
            - UserJwtFilter
jwt:
  secret: moondysmellwebapplicationsecret
  expiration-second: 172800  #48시간
#  expiration-second: 259200  #72시간
#  expiration-second: 10  #10초



