server:
  port: 8888
spring:
  name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/smellHyang/devstagram-configs
          search-paths: user, posts, meetup, gateway


#actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"