server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/smellHyang/devstagram-configs.git

#actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"

