server:
  port: 9092
  forward-headers-strategy: framework

spring:
  application:
    name: meetupservice
  profiles:
    active: default
    include: db
  config:
    import: "optional:configserver:"
url:
  gateway: "http://localhost:8888"