server:
  port: 9092

spring:
  application:
    name: meetupservice
  profiles:
    active: default
    include: db
  config:
    import: "optional:configserver:"
url:
  gateway: "http://localhost:9999/api/meetup"